### ISSUE TITLE
WebP images not visible in iOS

### ISSUE THREAD

**Issue by cfstras** [flipdot/0xA.flipdot.org#4]
looks very sad :(
![DFBCB169-E1B0-4F57-999B-61C0DAFE0344](https://user-images.githubusercontent.com/1156864/64882523-944eb700-d65d-11e9-9b37-d7b8608fe33f.png)

**Comment by flxai** [comment]
Does this also affect Chromium for iOS?

**Comment by flxai** [comment]
The `png` branch now uses PNG images instead. They're about 10 times bigger than their WebP counterpart. Please build in detection for browsers unable to use WebP to keep acceptable loading times, so it can be merged into `master`.

**Comment by nikeee** [comment]
> Does this also affect Chromium for iOS?

It should, since there are no other browser engines other than safari allowed on iOS.

 @icks Have you tried [pngcrush](https://pngcrush.com)?

Edit:
I added a fallback using the [HTML picture element](https://github.com/flipdot/0xA.flipdot.org/commit/491cabdac169f6a709014f37cb81cca521e4f9df) in 491cabdac169f6a709014f37cb81cca521e4f9df.

**Comment by flxai** [comment]
Just tried pngcrush for `badge.png`, but it seems that it already is optimal:

> Saved 0 bytes

Thanks for the iOS info and fallback.

**Comment by nikeee** [comment]
The Fallback was only added for the map. Do we need one for the badge as well?
